### ISSUE TITLE
Unexpected prefix displayed in documentation

### ISSUE THREAD

**Issue by cthoyt** [mapping-commons/semantic-mapping-vocabulary#4]
Why does `ns2` appear as the prefix in https://mapping-commons.github.io/semantic-mapping-vocabulary/? Shouldn't this be `semapv`?

<img width="1114" alt="Screen Shot 2022-08-02 at 13 51 03" src="https://user-images.githubusercontent.com/5069736/182367826-bf315ead-214b-4c93-a54f-0b5c8dd62aeb.png">

**Comment by matentzn** [comment]
Yeah I think this is based on whatever prefixes I have declared in the turtle file used for generating the docs. I can fix it.

**Comment by matentzn** [comment]
Merci. :)
